#!/usr/bin/env python3
"""Generate the reference documentation from source.

Three files are derived, never hand-edited:

    docs/reference/API.md        every @frappe.whitelist endpoint
    docs/reference/DOCTYPES.md   every DocType and field
    docs/reference/HOOKS.md      hooks.py registrations

Rationale: a hand-maintained API list is wrong within one sprint, and for a
Frappe app the whitelist list *is* the public HTTP surface — the one thing that
must not drift. Run after touching an endpoint, a DocType or hooks.py:

    python3 scripts/gen-docs.py

Prose documentation (ARCHITECTURE, OPERATIONS, SECURITY) is hand-written and
never touched by this script.
"""

from __future__ import annotations

import ast
import json
import pathlib
import subprocess
from ast import literal_eval as _lit   # safe AST-only parser, not builtin eval
from dataclasses import dataclass, field

ROOT = pathlib.Path(__file__).resolve().parent.parent
APP = ROOT / "vansale"
OUT = ROOT / "docs" / "reference"

# Names that count as an in-body permission check. Presence is a positive
# signal; absence is flagged for review, not asserted as a hole — many
# endpoints are safe because every query is scoped to frappe.session.user.
PERM_CALLS = (
    "has_permission",
    "check_permission",
    "get_roles",
    "PermissionError",
    "ignore_permissions=False",
)

BANNER = (
    "<!-- GENERATED BY scripts/gen-docs.py - DO NOT EDIT BY HAND.\n"
    "     Edit the source, then re-run: python3 scripts/gen-docs.py -->\n"
)


@dataclass
class Endpoint:
    module: str
    name: str
    args: list
    methods: list
    allow_guest: bool
    summary: str
    perm_checked: bool
    lineno: int
    source_file: str


@dataclass
class DocTypeInfo:
    name: str
    issingle: bool
    istable: bool
    module: str
    fields: list = field(default_factory=list)
    permissions: list = field(default_factory=list)


def _dotted(path: pathlib.Path) -> str:
    rel = path.relative_to(ROOT).with_suffix("")
    return ".".join(rel.parts)


def _first_sentence(doc) -> str:
    if not doc:
        return ""
    return " ".join(doc.strip().split("\n\n")[0].split())


def collect_endpoints() -> list:
    out = []
    for path in sorted(APP.rglob("*.py")):
        body_src = path.read_text()
        try:
            tree = ast.parse(body_src)
        except SyntaxError:
            continue
        for node in ast.walk(tree):
            if not isinstance(node, (ast.FunctionDef, ast.AsyncFunctionDef)):
                continue
            for dec in node.decorator_list:
                call = dec if isinstance(dec, ast.Call) else None
                target = call.func if call else dec
                if "whitelist" not in ast.unparse(target):
                    continue
                kw = {k.arg: ast.unparse(k.value) for k in (call.keywords if call else [])}
                methods = []
                if "methods" in kw:
                    try:
                        methods = _lit(kw["methods"])
                    except Exception:
                        methods = [kw["methods"]]

                args = []
                a = node.args
                defaults = [None] * (len(a.args) - len(a.defaults)) + list(a.defaults)
                for arg, default in zip(a.args, defaults):
                    if arg.arg == "self":
                        continue
                    ann = ": " + ast.unparse(arg.annotation) if arg.annotation else ""
                    dflt = " = " + ast.unparse(default) if default is not None else ""
                    args.append(f"{arg.arg}{ann}{dflt}")

                fn_src = ast.get_source_segment(body_src, node) or ""
                out.append(Endpoint(
                    module=_dotted(path),
                    name=node.name,
                    args=args,
                    methods=methods,
                    allow_guest=kw.get("allow_guest") == "True",
                    summary=_first_sentence(ast.get_docstring(node)),
                    perm_checked=any(p in fn_src for p in PERM_CALLS),
                    lineno=node.lineno,
                    source_file=str(path.relative_to(ROOT)),
                ))
    return sorted(out, key=lambda e: (e.module, e.name))


def collect_doctypes() -> list:
    out = []
    for path in sorted(APP.rglob("doctype/*/*.json")):
        try:
            d = json.loads(path.read_text())
        except json.JSONDecodeError:
            continue
        if d.get("doctype") != "DocType":
            continue
        out.append(DocTypeInfo(
            name=d.get("name", path.stem),
            issingle=bool(d.get("issingle")),
            istable=bool(d.get("istable")),
            module=d.get("module", ""),
            fields=d.get("fields", []),
            permissions=d.get("permissions", []),
        ))
    return sorted(out, key=lambda t: t.name)


def collect_hooks() -> dict:
    tree = ast.parse((APP / "hooks.py").read_text())
    wanted = (
        "doc_events", "after_migrate", "fixtures", "website_redirects",
        "website_route_rules", "boot_session", "after_request",
        "scheduler_events", "override_doctype_class", "role_home_page",
    )
    found = {}
    for node in tree.body:
        if not isinstance(node, ast.Assign):
            continue
        for t in node.targets:
            if isinstance(t, ast.Name) and t.id in wanted:
                try:
                    found[t.id] = _lit(node.value)
                except Exception:
                    found[t.id] = ast.unparse(node.value)
    return found


def app_version() -> str:
    try:
        return subprocess.run(
            ["git", "describe", "--tags", "--always", "--dirty"],
            cwd=ROOT, capture_output=True, text=True, check=True,
        ).stdout.strip()
    except Exception:
        return "unknown"


def write_api(endpoints: list) -> None:
    guest = [e for e in endpoints if e.allow_guest]
    unchecked = [e for e in endpoints if not e.perm_checked and not e.allow_guest]

    lines = [
        BANNER,
        "# API reference",
        "",
        "Every `@frappe.whitelist()` function is a **public HTTP endpoint** reachable at",
        "`/api/method/<dotted.path>`. This file is the complete list.",
        "",
        f"- **{len(endpoints)} endpoints**",
        f"- **{len(guest)} reachable without login** (`allow_guest=True`)",
        f"- **{len(unchecked)} with no in-body permission call** - see the note below",
        "",
        "## Guest-reachable endpoints",
        "",
        "These answer before any login. Each needs a justification in its docstring.",
        "",
        "| Endpoint | Methods | Summary |",
        "| --- | --- | --- |",
    ]
    for e in guest:
        lines.append(f"| `{e.module}.{e.name}` | {', '.join(e.methods) or '-'} | {e.summary or '-'} |")

    lines += [
        "",
        "## Endpoints without an explicit permission call",
        "",
        "Absence is **not** proof of a hole: most are safe because every query is scoped",
        "to `frappe.session.user`, or they only read reference data a Van User already",
        "holds DocType read permission on. This is a review list, not a bug list - but",
        "anything here that writes, or reads another user's data, needs an explicit",
        "`frappe.has_permission` call.",
        "",
        "| Endpoint | Args |",
        "| --- | --- |",
    ]
    for e in unchecked:
        lines.append(f"| `{e.module}.{e.name}` | {', '.join(e.args) or '-'} |")

    lines += ["", "## All endpoints by module", ""]
    current = None
    for e in endpoints:
        if e.module != current:
            current = e.module
            lines += ["", f"### `{current}`", ""]
        flags = []
        if e.allow_guest:
            flags.append("**GUEST**")
        if e.methods:
            flags.append("/".join(e.methods))
        if not e.perm_checked and not e.allow_guest:
            flags.append("_no perm call_")
        head = f"#### `{e.name}`"
        if flags:
            head += " - " + " / ".join(flags)
        lines += [head, ""]
        if e.summary:
            lines += [e.summary, ""]
        sig = ", ".join(e.args)
        lines += [
            "```",
            f"/api/method/{e.module}.{e.name}",
            f"({sig})" if sig else "(no arguments)",
            "```",
            "",
            f"<sub>{e.source_file}:{e.lineno}</sub>",
            "",
        ]
    (OUT / "API.md").write_text("\n".join(lines) + "\n")


def write_doctypes(doctypes: list) -> None:
    lines = [
        BANNER,
        "# DocType reference",
        "",
        "Schema shipped by the app. A Single has exactly one record site-wide; a child",
        "table has no list view and is only reachable through its parent.",
        "",
        "| DocType | Kind | Fields |",
        "| --- | --- | --- |",
    ]
    for t in doctypes:
        kind = "Single" if t.issingle else ("Child table" if t.istable else "Document")
        real = [f for f in t.fields if f.get("fieldtype") not in ("Section Break", "Column Break")]
        anchor = t.name.lower().replace(" ", "-")
        lines.append(f"| [{t.name}](#{anchor}) | {kind} | {len(real)} |")

    for t in doctypes:
        kind = "Single" if t.issingle else ("Child table" if t.istable else "Document")
        lines += ["", f"## {t.name}", "", f"*{kind}*", "",
                  "| Field | Type | Options / default | Notes |",
                  "| --- | --- | --- | --- |"]
        for f in t.fields:
            ft = f.get("fieldtype", "")
            if ft in ("Section Break", "Column Break"):
                label = f.get("label") or ""
                if label:
                    lines.append(f"| | | | **-- {label} --** |")
                continue
            opts = str(f.get("options") or "").replace("\n", " / ")
            if len(opts) > 60:
                opts = opts[:57] + "..."
            if f.get("default") is not None:
                opts = (opts + " / " if opts else "") + f"default `{f['default']}`"
            notes = []
            if f.get("reqd"):
                notes.append("required")
            if f.get("read_only"):
                notes.append("read-only")
            if f.get("depends_on"):
                notes.append(f"shown when `{f['depends_on']}`")
            desc = " ".join(str(f.get("description") or "").split())
            if desc:
                notes.append(desc if len(desc) <= 160 else desc[:157] + "...")
            lines.append(f"| `{f.get('fieldname','')}` | {ft} | {opts or '-'} | {'; '.join(notes) or '-'} |")
        roles = ", ".join(f"`{p.get('role')}`" for p in t.permissions if p.get("role"))
        if roles:
            lines += ["", f"**Roles with DocPerms:** {roles}", ""]
    (OUT / "DOCTYPES.md").write_text("\n".join(lines) + "\n")


def write_hooks(hooks: dict) -> None:
    lines = [
        BANNER,
        "# Hooks reference",
        "",
        "From `vansale/hooks.py`. Anything here runs against documents this app does not",
        "own, so it is the first list to check when another app's behaviour changes",
        "unexpectedly.",
        "",
    ]
    if isinstance(hooks.get("doc_events"), dict):
        lines += ["## `doc_events`", "", "| DocType | Event | Handler |", "| --- | --- | --- |"]
        for dt, events in hooks["doc_events"].items():
            for event, handlers in (events or {}).items():
                for h in handlers if isinstance(handlers, list) else [handlers]:
                    lines.append(f"| {dt} | `{event}` | `{h}` |")
        lines.append("")

    for key in ("after_migrate", "after_request", "boot_session", "role_home_page"):
        if key in hooks:
            val = hooks[key]
            lines += [f"## `{key}`", ""]
            for h in val if isinstance(val, list) else [val]:
                lines.append(f"- `{h}`")
            lines.append("")

    if "fixtures" in hooks:
        lines += ["## `fixtures`", "",
                  "Exported with `bench export-fixtures`, re-imported on every `bench migrate`.",
                  "", "```json", json.dumps(hooks["fixtures"], indent=2), "```", ""]

    for key in ("website_redirects", "website_route_rules"):
        if key in hooks:
            lines += [f"## `{key}`", "", "```json", json.dumps(hooks[key], indent=2), "```", ""]

    (OUT / "HOOKS.md").write_text("\n".join(lines) + "\n")


def main() -> None:
    OUT.mkdir(parents=True, exist_ok=True)
    endpoints = collect_endpoints()
    doctypes = collect_doctypes()
    hooks = collect_hooks()
    write_api(endpoints)
    write_doctypes(doctypes)
    write_hooks(hooks)
    guest = sum(1 for e in endpoints if e.allow_guest)
    unchecked = sum(1 for e in endpoints if not e.perm_checked and not e.allow_guest)
    print(f"version     : {app_version()}")
    print(f"API.md      : {len(endpoints)} endpoints ({guest} guest, {unchecked} unchecked)")
    print(f"DOCTYPES.md : {len(doctypes)} doctypes")
    print(f"HOOKS.md    : {len(hooks)} hook groups")


if __name__ == "__main__":
    main()
